apiVersion: v1
kind: Service
metadata:
  name: html-webserver
  labels:
    app: html-webserver
spec:
  ports:
    - port: 80
      nodePort: 31000
  selector:
    app: html-webserver
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-webserver
  labels:
    app: html-webserver
spec:
  selector:
    matchLabels:
      app: html-webserver
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: html-webserver
        tier: frontend
    spec:
      containers:
      - image: httpd
        name: html-webserver
        ports:
        - containerPort: 80
          name: html-webserver
        volumeMounts:
        - name: html-webserver-persistent-storage
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: html-webserver-persistent-storage
        persistentVolumeClaim:
          claimName: html-pv-claim
